### ISSUE TITLE
Not compatible with kernelsu

### ISSUE THREAD

**Issue by uaevuon** [AdguardTeam/adguardcert#42]
Will it support kernelsu?

I just came back to magisk cause this module does not do anything on kernelsu.

**Comment by XAlboX** [comment]
It needs Zygisk to work.
https://github.com/Dr-TSNG/ZygiskOnKernelSU

**Comment by uaevuon** [comment]
> It needs Zygisk to work. https://github.com/Dr-TSNG/ZygiskOnKernelSU

Latest 2.0 beta versions do not require zygisk.

**Comment by Rtizer-9** [comment]
The latest 2.0 beta 4 doesn't need either zygisk or riru to work and is completely compatible with ksu but it needs ag version 4.2 something nightlies to work.

You need to go into settings > filtering> network> https filtering> security certificate and install both the certificates including the secondary one (yes there are two certificates in latest nightlies, I too missed it at first) and then flash latest beta zip of this module in ksu and then reboot.

**Comment by uaevuon** [comment]
![Screenshot_20230827-021712_Play_Integrity_API_Checker](https://github.com/AdguardTeam/adguardcert/assets/3542715/d9600c17-aa02-4cac-a738-2e060582b6a6)
On latest nightly(v4.2.56), I guess it really is not compatible.
Installed two certs, but the module do not move the cert to system properly. It does not appear on settings app and make this error on some apps. The screenshot is from this app. [](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck)

**Comment by Rtizer-9** [comment]
The order of doing things is of importance here.

You first need to give ag root permissions manually using ksu and then only the secondary/intermediate certificate menu will appear in the location I mentioned above.

Now after this only you'll be able to install that intermediate certificate.

When the installation is done it'll show that both the certificates are installed but upper one can be moved to system.

AFTER this, manually go to ksu and then flash the module zip and reboot.

I personally checked it on v4.2.56 nightly with the app you mentioned above.

Do remember that some apps with very heavy security employing things SSL pinning do not allow users to anyhow analyse the traffic of their application which includes having an app like ag in your phone which lets you see the requests, so they'll still not work even with all this setup in most cases.

The above setup will still work with almost all apps because the certificate is in the system store.

**Comment by uaevuon** [comment]
I did same thing on Magisk canary and it works. ssl errors do not appear on magisk installed device. The only difference here is kernelsu vs magisk. If it worked on your side, I have no idea why this kernelsu issue happens on my device only.

**Comment by Rtizer-9** [comment]
I would suggest starting from a fresh state.

Take Adguard settings backup and then uninstall everything including ag and the module and then reboot.

Install ag now and give root permissions, then install both the certificates and import settings from backup and after all this when ag certificate show both the certificates have been installed properly and is asking for moving the cert into system then install the Module in ksu and reboot. Everything should work fine now.

If you have 2-3 certificates in the user store from leftovers then I'd suggest removing all of them too during uninstallation of ag.

**Comment by uaevuon** [comment]
Finally find out the solution. I have to set those app in kernelsu as custom template and turn off the option.

**Comment by trashforreal** [comment]
how did you get that to work? mine still has same problem till date

**Comment by XAlboX** [comment]
> how did you get that to work? mine still has same problem till date 

Try disabling "unmount modules by default" in KSU.
This could make root permissions visible for some apps like banking ones, in those apps you should set a custom profile and enable the unmount modules option to hide modules (Root(?))
Let me know 🤔
